name             'task1'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures task1'
long_description 'Installs/Configures task1'
version          '0.1.0'
